/*MICRO DESAFIO PASO-1 
1-INSERTAR EN TABLA GENRES */

INSERT INTO GENRES ( NAME,RANKING, ACTIVE) 
VALUES ('INVESTIGACION', 13, 1) *LISTO*

/*2- ACTUALIZAR EL NUEVO REGISTRO */

UPDATE GENRES 
SET NAME = 'INVESTIGACIÓN CIENTÍFICA' 
WHERE NAME = 'INVESTIGACIÓN'  

/*3- ELIMINAR REGISTRO DE NOMBRE */

DELETE FROM GENRES 
WHERE NAME = 'INVESTIGACÍON CIENTÍFICA' 

/*4- MOSTRAR REGISTROS DE TABLA MOVIES */

SELECT * FROM MOVIES 

/*5- MOSTRAR RATING NOMBRE APELLIDO DE ACTORES */

SELECT NOMBRE, APELLIDO, RATING
FROM ACTORS 

/*6- MOSTRAR TITULO DE TODAS LAS SERIES */

SELEC TITLE AS TITULO 
FROM SERIES; 

-------------------------------------- 

/*MICRO DESAFIO PASO 2 
1-MOSTRAR NOMBRE Y APELLIDO DE ACTORES CON RATING MAYOR A 7.5 */

SELECT FIRST_NAME, LAST_NAME, RATING 
FROM ACTORS
WHERE RATING > 7.5; 


/*2- MOSTRAR TITULO DE PELICULAS, RATING Y PREMIOS CON RATING MAYOR A 7.5 Y CON + 2 PREMIOS */

SELECT TITLE, RATING, AWARDS
FROM MOVIES
WHERE RATING > 7.5
AND AWARDS > 2; 


/*3-MOSTRAR TITULO DE PELICULAS Y RATING ORDENADAS POR RATING ASCENDENTE*/

SELECT TITTLE, RATING
FROM MOVIES
ORDER BY RATING; 
-----------------------------------------

/*MICRO DESAFIO PASO 3 
1- MOSTRAR TITULOS DE PRIMERAS 3 PELICULAS EN LA BASE DE DATOS */

SELECT TITLE
FROM MOVIES 
LIMIT 3; 

/*2-MOSTAR TOP 5 DE MAYOR RATING */

SELECT TITLE, RATING
FROM MOVIES
ORDER BY RATING DESC
LIMIT 5 


/*3- MOSTRAR TOP 5 A 10 DE MAYOR RATING*/

SELECT TITLE, RATING
FROM MOVIES
ORDER BY RATING DESC
LIMIT 5
OFFSET 5; 


/*4- LISTAR TOP 10 ACTORES (PRIMERA PAGINA) */

SELECT FIRST_NAME, LAST_NAME
FROM ACTORS 
LIMIT 10; 

/*4.1 Y LUEGO USAR OFFSET PARA TRAER PAGINA 3. */

SELECT FIRST_NAME, LAST_NAME 
FROM ACTORS
LIMIT 10 
OFFSET 20; 

--------------------------------------
/*MICRO DESAFIO 4 
1-MOSTRAR TITULO Y RATING DE TODAS LAS PELICULAS CON TITULO 'HARRY POTTER' 
TUVE QUE UTILIZAR LIKE YA QUE ASI SE REFLEJAN LAS PELICULAS CUYO NOMBRE HARRY POTTER*/

SELECT TITLE, RATING 
FROM MOVIES 
WHERE FIRST_NAME LIKE 'HARRY POTTER%' 

/*2- MOSTRAR TODOS LOS ACTORES CON NOMBRE EMPIECE CON 'SAM'*/

SELECT * FROM ACTORS 
WHERE FIRST_NAME LIKE '%SAM%'

/*3- MOSTRAR TITULO DE PELICULAS QUE SALIERON ENTRE 2004 - 2008 */

SELECT * FROM MOVIES
WHERE RELEASE_DATE
BETWEEN "2004-01-01"
AND "2009-01-01"; 

